name: "Build and test"

on:
  workflow_call

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: Build
      run: dotnet build ./arc-validate-package-registry.sln --configuration Release
    - name: Test
      run: dotnet test ./arc-validate-package-registry.sln --configuration Release --no-build

  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: Build
      run: dotnet build ./arc-validate-package-registry.sln --configuration Release
    - name: Test
      run: dotnet test ./arc-validate-package-registry.sln --configuration Release --no-build

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: Build
      run: dotnet build ./arc-validate-package-registry.sln --configuration Release
    - name: Test 
      run: dotnet test ./arc-validate-package-registry.sln --configuration Release --no-build