name: "Build and test"

on:
  workflow_call

jobs:
  windows:
    runs-on: windows-latest
    name: "[windows] Build and test"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: Build
      run: dotnet build ./arc-validate-package-registry.sln
    - name: Test
      run: dotnet test ./arc-validate-package-registry.sln

  ubuntu:
    runs-on: ubuntu-latest
    name: "[ubuntu] Build and test"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: Build
      run: dotnet build ./arc-validate-package-registry.sln
    - name: Test
      run: dotnet test ./arc-validate-package-registry.sln

  macos:
    runs-on: macos-latest
    name: "[macOS] Build and test"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: Build
      run: dotnet build ./arc-validate-package-registry.sln
    - name: Test
      run: dotnet test ./arc-validate-package-registry.sln