name: "Build and test solution"

on:
  workflow_call:
    inputs: 
      solution: 
        description: "The solution file to build and test"
        type: string
        required: true
        default: "arc-validate-package-registry.sln"
      configuration:
        type: string
        description: "The configuration to build and test"
        required: true
        default: "Release"
      windows:
        type: boolean
        description: "wether to run on windows"
        default: true
      ubuntu:
        type: boolean
        description: "wether to run on ubuntu"
        default: true
      macos:
        type: boolean
        description: "wether to run on macos"
        default: true

jobs:
  determine-strategy:
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: |
          win = if ${{ inputs.windows }} == true then 'windows-latest,' else ''
          ubu = if ${{ inputs.ubuntu }} == true then 'ubuntu-latest,' else ''
          mac = if ${{ inputs.macos }} == true then 'macos-latest' else ''
          echo "matrix: [${win}${ubu}${mac}]" >> $GITHUB_OUTPUT

  build-and-test:
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: Build
      run: dotnet build ${{ inputs.solution }} --configuration ${{ inputs.configuration }}
    - name: Test
      run: dotnet test ${{ inputs.solution }} --configuration ${{ inputs.configuration }} --no-build