name: "publish pending packages"

on:
  push:
    branches: ['main']
    paths:
      - 'src/StagingArea/**'
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'manually decide wether to dry run or publish to production'
        required: true
        default: true
        type: boolean

jobs:
  publish-pending-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
      - uses: actions/checkout@v4
      - name: decide on dry run
        run: |
          if [[ ${{ github.event_name == 'workflow_dispatch' }} == true ]]; then
            DRYRUN=${{ dry-run }}
          else
            DRYRUN=false
          fi
          echo "DRYRUN=$DRYRUN" >> $GITHUB_ENV
      - run: dotnet fsi scripts/publish-pending-packages.fsx {{env.DRYRUN}}
        env:
          APIKEY: ${{ secrets.APIKEY }}