name: "publish pending packages"

on:
  push:
    branches: ['main']
    paths:
      - 'src/PackageRegistryService/StagingArea/**'
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'dry run mode'
        required: true
        default: true
        type: boolean


jobs:
  publish-pending-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
      - uses: actions/checkout@v4
      - name: decide on dry run
        run: |
          if [[ ${{ github.event_name == 'workflow_dispatch' }} == true ]]; then
            dry_run=${{ inputs.dry-run }}
          else
            dry_run=false
          fi
          if [[ $dry_run == true ]]; then
            echo "DRYRUN=--dry-run" >> $GITHUB_ENV
          else
            :
          fi
      - run: dotnet fsi scripts/publish-pending-packages.fsx ${{ env.DRYRUN }}
        env:
          APIKEY: ${{ secrets.APIKEY }}