name: "Release Packages"

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
        description: "The build project target that packs the package"
jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x.x
    - name: Make build script executable
      run: chmod +x build.sh
    - name: Pack
      run: ./build.sh ${{ inputs.target }}
    - name: NuGet login (OIDC to temporary API key)
      uses: NuGet/login@v1
      id: nuget-login
      with:
        user: ${{ vars.NUGET_USER }}
    - name: push
      run: dotnet nuget push ./artifacts/packages/*.nupkg --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
